In [ ]:
# Pandas

In [ ]:
%pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [ ]:
#1D data structures in pandas

In [ ]:
#pandas series

In [ ]:
import pandas as pd

In [ ]:
s = pd.Series([10,20,30])

In [ ]:
s

0    10
1    20
2    30
dtype: int64

In [ ]:
s2 = pd.Series([9,74,87])

In [ ]:
s2

0     9
1    74
2    87
dtype: int64

In [ ]:
# costom index

In [ ]:
s = pd.Series([10,20,30],index =['a','b','c'])

In [ ]:
s

a    10
b    20
c    30
dtype: int64

In [ ]:
series = pd.Series(['sanskruti',18,85],index=['name','age','marks'])

In [ ]:
series

name     sanskruti
age             18
marks           85
dtype: object

In [ ]:
# From Dictionary

In [ ]:
data = {'name':"Rahul",'age':25,'marks':90}

In [ ]:
data

{'name': 'Rahul', 'age': 25, 'marks': 90}

In [ ]:
s = pd.Series(data)

In [ ]:
s

name     Rahul
age         25
marks       90
dtype: object

In [ ]:
# from single value

In [ ]:
s = pd.Series(5,index=[0,1,2,3])

In [ ]:
s

0    5
1    5
2    5
3    5
dtype: int64

In [ ]:
s = pd.Series('sanskruti',index=['a','b','c','d','e'])

In [ ]:
s

a    sanskruti
b    sanskruti
c    sanskruti
d    sanskruti
e    sanskruti
dtype: object

In [ ]:
# Attributes

In [ ]:
s = pd.Series([10,20,30],index=['a','b','c'])

In [ ]:
s.values

array([10, 20, 30])

In [ ]:
s.index

Index(['a', 'b', 'c'], dtype='object')

In [ ]:
s.dtype

dtype('int64')

In [ ]:
s.shape

(3,)

In [ ]:
s.size

3

In [ ]:
# Data Manipulation

In [ ]:
s = pd.Series([1,2,3])

In [ ]:
print(s*3)

0    3
1    6
2    9
dtype: int64

In [ ]:
# Handling missing values

In [ ]:
s = pd.Series([1,None,3])

In [ ]:
s

0    1.0
1    NaN
2    3.0
dtype: float64

In [ ]:
s.isnull()

0    False
1     True
2    False
dtype: bool

In [ ]:
s.dropna()

0    1.0
2    3.0
dtype: float64

In [ ]:
s.fillna(0)

0    1.0
1    0.0
2    3.0
dtype: float64

In [ ]:
# Indexing

In [ ]:
s1 = pd.Series([10,20,30],index=['a','b','c'])

In [ ]:
s1

a    10
b    20
c    30
dtype: int64

In [ ]:
s1['a']

np.int64(10)

In [ ]:
s1['c']

np.int64(30)